### PR TITLE
Fix typo: MecCab -> MeCab

### PR DESCRIPTION
**Pull request by chocoby**
Fixed typo in file README.md

### CODE REVIEW

**Comment by johtani** [comment]
Hi @chocoby 

Thanks for the PR. Please could I ask you to sign the CLA so that we can merge it in.
http://www.elasticsearch.org/contributor-agreement/

**Comment by chocoby** [comment]
Sorry... I signed the CLA now.

**Comment by johtani** [comment]
No problem!

Thanks, merged.

**Comment by chocoby** [comment]
Thank you! :smile:

**Pull request merged**
